lw/urls.py
from django.conf.urls import patterns, include, url
from invites.views import *
from django.views.generic import TemplateView

import os.path
media = os.path.join(os.path.dirname(__file__), 'media')

# URL patterns for invite campaign pages

urlpatterns = patterns('',
    (r'^$', landing),
    (r'^emailadded/$', processInviteRequest),
    (r'^fblogin/$', facebook_login),
    (r'^fbsuccess/$', facebook_login_success),
    (r'^twitter/$', auth),
    (r'^result/$', info),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':media}),
)

# URL patterns for the main application

urlpatterns += patterns('',
    (r'^m/', include('main.urls')),
)

main/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

class SignupFormA(forms.Form):
    email = forms.EmailField()
    
    def clean_email(self):
        email = self.cleaned_data['email']
        
        try:
            User.objects.get(email = email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError('This email address has been linked to another account on Likewyss.')
        
class SignupFormB(forms.Form):
    fullname = forms.CharField(max_length=64)
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length = 32, widget = forms.PasswordInput())
    
    def clean_username(self):
        user = self.cleaned_data['username']
        
        try:
            u = User.objects.get(username = user)
        except ObjectDoesNotExist:
            return user
        raise forms.ValidationError('Username already taken. Please pick another one.')
    
class PostingForm(forms.Form):
    text = forms.CharField(max_length=250, widget=forms.Textarea())

lw/templates/pages/feed.html
{% extends 'parent/bicolumnar-base.html' %}

{% block title %}Likewyss{% endblock %}

{% block content %}
<div class="row">
	<div class="container">
		<div class="span6">
			{% include 'includes/posting.html' %}
		</div>
	</div>
</div>
{% endblock %}

lw/templates/pages/profile.html
{% extends 'parent/bicolumnar-base.html' %}

{% block title %}{{ fullname }}{% endblock %}

{% block left-content %}
<div id="basic-info-wrapper" class="span4 padded-wrapper well">
	<h4>{{ fullname }}</h4>
	<h6>{{ username }}</h6>
</div>

<div id="added-info-wrapper" class="span4 well">
	<ul>	
		<li class="span1"><span class="statistic">745</span> <span class="stattext">posts</span></li>
		<li class="span1"><span class="statistic">3,583</span> <span class="stattext">starred</span></li>
		<li class="span1"><span class="statistic">1,209</span> <span class="stattext">fans</span></li>
	</ul>
	<div class="span2">
		<a href="https://www.facebook.com/{{ facebook }}" target='_blank'><button class="btn btn-facebook"><i class="icon-facebook"></i></button></a>
		<a href="https://www.twitter.com/{{ twitter }}" target='_blank'><button class="btn btn-twitter"><i class="icon-twitter"></i></button></a>
		<a href="https://plus.google.com/{{ googleplus }}" target='_blank'><button class="btn btn-google-plus"><i class="icon-google-plus"></i></button></a>
	</div>
</div>
{% endblock %}

{% block right-content %}
<div class="padded-wrapper" >
	{% if posts %}
	{% for post in posts %}
	<div class="span4 well post-wrapper">
		<h5 class="poster-name">{{ post.user.get_full_name }}</h5>
		<h6 class="post-time">{{ post.time }}</h6>
		<p class="post-text">{{ post.text }}</p>
	</div>
	{% endfor %}
	{% else %}
	<p class="error">{{ fullname }} has not posted anything yet.</p>
	{% endif %}
</div>	
{% endblock %}

lw/templates/pages/settings.html
{% extends 'parent/bicolumnar-base.html' %}

{% block title %}Settings{% endblock %}

{% block left-content %}
<div id="basic-info-wrapper" class="span4 padded-wrapper well">
	<h4><a href="/u/{{ user.username }}">{{ user.get_full_name }}</a></h4>
	<h6>{{ user.username }}</h6>
</div>

<div id="added-info-wrapper" class="span4 well">
	<ul>	
		<li class="span1"><span class="statistic">7,450</span> <span class="stattext">posts</span></li>
		<li class="span1"><span class="statistic">3,583</span> <span class="stattext">starred</span></li>
		<li class="span1"><span class="statistic">1,209</span> <span class="stattext">fans</span></li>
	</ul>
	
	<div class="span2" id="social">
		<a href="https://www.facebook.com/{{ facebook }}" target='_blank'><button class="btn btn-facebook"><i class="icon-facebook"></i></button></a>
		<a href="https://www.twitter.com/{{ twitter }}" target='_blank'><button class="btn btn-twitter"><i class="icon-twitter"></i></button></a>
	</div>
</div>
{% endblock %}

{% block right-content %}
<div class="span4 padded-wrapper well">
	<h1>Settings</h1>
	<form action="." method="post">
		{% csrf_token %}
		<input type="text" name="fullname" id="id_fullname" placeholder="{{ user.get_full_name }}" />
		<input type="text" name="username" id="id_username" placeholder="{{ user.username }}" />
		<input type="text" name="password" id="id_password" placeholder="{{ user.email }}" />
		<input type="password" name="password" id="id_password" placeholder="Change your password" />
		<button type="submit" class="btn btn-success"><i class="icon-cogs"></i>&nbsp;&nbsp;Save settings</button>
	</form>
</div>
{% endblock %}