lw/urls.py
from django.conf.urls import patterns, include, url
from invites.views import *
from django.views.generic import TemplateView

import os.path
media = os.path.join(os.path.dirname(__file__), 'media')

# URL patterns for invite campaign pages

urlpatterns = patterns('',
    (r'^$', landing),
    (r'^emailadded/$', processInviteRequest),
    (r'^fblogin/$', facebook_login),
    (r'^fbsuccess/$', facebook_login_success),
    (r'^twitter/$', auth),
    (r'^result/$', info),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':media}),
)

# URL patterns for the main application

urlpatterns += patterns('',
    (r'^m/', include('main.urls')),
)

invites/models.py
from django.db import models

class InviteEmails(models.Model):
    emailaddress = models.EmailField()

invites/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from invites.models import InviteEmails

class InviteForm(forms.Form):
    emailaddress = forms.EmailField(label='')
    
    # Redundancy checker runs through the existing list of email addresses and checks for repeated email signups, if any and throws a validation error. In addition,
    # we can have a validation in the views.py file also.
    
    def RedundancyChecker(self):
        email = self.cleaned_data['emailaddress']
        
        try:
            InviteEmails.objects.get(emailaddress = email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError('Email already exists in the database.')

invites/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from invites.forms import InviteForm
from django.core.urlresolvers import reverse
from invites.models import InviteEmails
from main.models import SignupHandler
from pyfb import Pyfb

import tweepy
import random
import locale
locale.setlocale(locale.LC_ALL, 'en_US')

numberofemails = InviteEmails.objects.count()
numberleft = locale.format('%d', 2500 - numberofemails, grouping = True)

def landing(request):
    form = InviteForm()
        
    var = RequestContext(request, {
        'form':form,
        'number':numberleft
    })
    
    return render_to_response('invites/landing.html', var)

def emailInstanceCreate(email, fb=False, twitter=False):
    randomnumber = random.randint(0,100000)
    emailadd = InviteEmails.objects.create(emailaddress = email, id=numberofemails+1)
    signuphandle = SignupHandler.objects.create(emailaddress = email, identifiernum = randomnumber)

def processInviteRequest(request):
    if request.method=='POST':
        form = InviteForm(request.POST)
        
        if form.is_valid():
            email = form.cleaned_data['emailaddress']
            try:
                emailadd = InviteEmails.objects.get(emailaddress = email)
            except ObjectDoesNotExist:
                emailInstanceCreate(email)
                emailadd = InviteEmails.objects.get(emailaddress = email)
                return render_to_response('invites/result.html', RequestContext(request, {'email':emailadd, 'result':'success'}))
            return render_to_response('invites/result.html', RequestContext(request, {'email':emailadd, 'result':'existing'}))
        return HttpResponse('Error.')
    else:
        return HttpResponseRedirect('/')

def auth(request):
    oauth = tweepy.OAuthHandler(settings.TWITTER_APP_KEY, settings.TWITTER_APP_SECRET)

    auth_url = oauth.get_authorization_url(True)
    response = HttpResponseRedirect(auth_url)

    request.session['unauthed_token_tw'] = (oauth.request_token.key, oauth.request_token.secret) 
    return response

def callback(request):
    verifier = request.GET.get('oauth_verifier')
    oauth = tweepy.OAuthHandler(settings.TWITTER_APP_KEY, settings.TWITTER_APP_SECRET)
    token = request.session.get('unauthed_token_tw', None)
    # remove the request token now we don't need it
    request.session.delete('unauthed_token_tw')
    oauth.set_request_token(token[0], token[1])
    # get the access token and store
    try:
        oauth.get_access_token(verifier)
    except tweepy.TweepError:
        print 'Error, failed to get access token'
    request.session['access_key_tw'] = oauth.access_token.key
    request.session['access_secret_tw'] = oauth.access_token.secret

    emailInstanceCreate(authorized_tokens['email'])

    response = HttpResponseRedirect('/result/')
    return response

def check_key(request):
    """
    Check to see if we already have an access_key stored, if we do then we have already gone through 
    OAuth. If not then we haven't and we probably need to.
    """
    try:
        access_key = request.session.get('access_key_tw', None)
        if not access_key:
            return False
    except KeyError:
        return False
    return True

def info(request):
    if check_key(request):
        api = get_api(request)
        user = api.me()
        return render_to_response('invites/twttr.html', {'user' : user})
    else:
        return HttpResponseRedirect(reverse('main'))

def facebook_login(request):
    facebook = Pyfb(settings.FACEBOOK_APP_ID)
    return HttpResponseRedirect(facebook.get_auth_code_url(redirect_uri=settings.FACEBOOK_REDIRECT_URL))

def facebook_login_success(request):
    code = request.GET.get('code')    
    facebook = Pyfb(settings.FACEBOOK_APP_ID)
    facebook.get_access_token(settings.FACEBOOK_SECRET_KEY, code, redirect_uri=settings.FACEBOOK_REDIRECT_URL)
    me = facebook.get_myself()

    try:
        email = InviteEmails.objects.get(emailaddress = me.email)
    except ObjectDoesNotExist:
        emailInstanceCreate(me.email)
        email = InviteEmails.objects.get(emailaddress = me.email)

        return render_to_response('invites/result.html', RequestContext(request, {'email':email, 'result':'success'}))
    return render_to_response('invites/result.html', RequestContext(request, {'email':email, 'result':'existing'}))

lw/templates/invites/base.html
<!DOCTYPE HTML>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	
	<link rel="stylesheet" type="text/css" href="/media/css/basic.css" />
	<link rel="stylesheet" type="text/css" href="/media/css/landing.css" />
	
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=626969007330520";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</head>

<body>
	{% block content %}{% endblock %}
</body>	

lw/templates/invites/landing.html
{% extends 'parent/landing-base.html' %}

{% block title %}Hello.{% endblock %}

{% block content %}
<div class="row">
	<div class="span9">
		<h1>Hello.</h1>
		<h3>Nice to meet us? Likewyss.</h3>
		<form action="/emailadded/" class="well" method="post">
			<p>Likewyss will be available only to select few people initially. Just {{ number }} slots left. Hurry up!</p>
			<input type="text" class="input-xxlarge" name="emailaddress" placeholder="Enter your email address" id="id_emailaddress" /><br>
			<button type="submit" class="input-xlarge btn btn-success" id="countmein">Count me in</button>
			<p>{% csrf_token %}</p>
		</form>
		<div class="well span8">
		<a href="/fblogin/"><button class="btn btn-facebook"><i class="icon-facebook">&nbsp;&nbsp;Connect with Facebook</i></button></a>&nbsp;&nbsp;
		<a href="twitter/"><button class="btn btn-twitter"><i class="icon-twitter">&nbsp;&nbsp;Connect with Twitter</i></button></a>&nbsp;&nbsp;
	</div>
	</div>
</div>

<div class="row-fluid">
	<div class="well span4">
		<h1><i class="icon-list"></i> News.</h1>
		<h6>Likewyss is an amazing platform that connects you to the things you love. Unlike Pulse, Flipboard, etc. we are not limited to a few magazines. Love startups? Get the best content on startups right on your feed. Period.</h6>
	</div>
	
	<div class="well span4">
		<h1><i class="icon-link"></i> Bonds.</h1>
		<h6>While making Likewyss as interest-centric as possible, we have also craftily and elegantly integrated socialization into the platform. Love someone's updates? Star him. Bump his posts up on your feed. Say hi. Today.</h6>
	</div>
	
	<div class="well span4">
		<h1><i class="icon-group"></i> People.</h1>
		<h6>The greatest content creators in the world are not newspapers or magazines. It is you, the people. Every piece of content on Likewyss will be created and owned by you. Start penning your thoughts. Now.</h6>
	</div>
</div>
{% endblock %}

lw/templates/invites/result.html
{% extends 'parent/landing-base.html' %}

{% block title %}
{% if result == 'success' %}
Successfully signed up
{% else %}
Please be patient
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
	<div class="span12">
	{% if result == 'success' %}
	<h1>Success.</h1>
	<div class="well">
		{% if email.throughfb == 1 %}
		<p>Thank you for using your Facebook account to signup.</p>
		{% elif email.throughtwitter == 1 %}
		<p>Thank you for using your Twitter account to signup.</p>
		{% endif %}
		<p>Your email address <b>{{ email.emailaddress }}</b> is at slot #{{ email.pk }}.<br>We will notify you once we are ready to welcome you into the site.</p></div>
	{% else %}
	<h1>Patience, please.</h1>
	<div class="well"><p>Wow, that curious huh? Good things come to those who wait.<br>Your email address{% if email.throughfb == 1 %} from your Facebook account {% elif email.throughtwitter == 1 %} from your Twitter account {% endif %} <b>{{ email.emailaddress }}</b> is already on our waiting list at slot #{{ email.pk }}.<br>We will notify you as soon as we are done.</p></div>
	{% endif %}
	<a href="/"><button type="submit" class="btn btn-info"><i class="icon-home"></i> Go home</button></a>
	<a href="https://www.facebook.com/likewyss" target="_blank"><button type="submit" class="btn btn-facebook"><i class="icon-facebook"></i>&nbsp;&nbsp;Find us on Facebook</button></a>
	<a href="https://www.twitter.com/likewyss" target="_blank"><button type="submit" class="btn btn-twitter"><i class="icon-twitter"></i>&nbsp;&nbsp;Track us on Twitter</button></a>
</div>

</div>
{% endblock %}

lw/templates/invites/twttr.html
<html>
<body>
		<div id="container">
			<img src="{{user.profile_image_url}}" />
			<h3>{{user.name}}</h3>
			<p>{{user.screen_name}}<p/>
			<a href="/logout/" title="logout">logout</a>
		</div>
</body>