lw/urls.py
from django.conf.urls import patterns, include, url
from invites.views import *
from django.views.generic import TemplateView

import os.path
media = os.path.join(os.path.dirname(__file__), 'media')

# URL patterns for invite campaign pages

urlpatterns = patterns('',
    (r'^$', landing),
    (r'^emailadded/$', processInviteRequest),
    (r'^fblogin/$', facebook_login),
    (r'^fbsuccess/$', facebook_login_success),
    (r'^twitter/$', auth),
    (r'^result/$', info),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':media}),
)

# URL patterns for the main application

urlpatterns += patterns('',
    (r'^m/', include('main.urls')),
)

main/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

class SignupFormA(forms.Form):
    email = forms.EmailField()
    
    def clean_email(self):
        email = self.cleaned_data['email']
        
        try:
            User.objects.get(email = email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError('This email address has been linked to another account on Likewyss.')
        
class SignupFormB(forms.Form):
    fullname = forms.CharField(max_length=64)
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length = 32, widget = forms.PasswordInput())
    
    def clean_username(self):
        user = self.cleaned_data['username']
        
        try:
            u = User.objects.get(username = user)
        except ObjectDoesNotExist:
            return user
        raise forms.ValidationError('Username already taken. Please pick another one.')
    
class PostingForm(forms.Form):
    text = forms.CharField(max_length=250, widget=forms.Textarea())

lw/templates/includes/nav.html
<div class="navbar navbar-fixed-top" id="primarynavigation">
	<div class="navbar-inner">
		<div class="container">
			<ul class="nav">
				<li class="active center">
					<a class="brand" href="/feed/">Likewyss</a>
				</li>
			</ul>
			
			<form action="/search/" method="get" class="navbar-search pull-left">
				<input type="text" class="search-query" name="q" placeholder="Search Likewyss" autocomplete="off">
			</form>
			
			<ul class="nav pull-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle='dropdown'>
						{{ user.get_full_name }}
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#postcompose"><i class="icon-pencil"></i>&nbsp;&nbsp;Compose a post</a></li>
						<li><a href="/u/{{ user.username }}"><i class="icon-user"></i>&nbsp;&nbsp;View profile</a></li>
						<li><a href="/settings/"><i class="icon-cogs"></i>&nbsp;&nbsp;Settings</a></li>
						<li><a href="/logout/"><i class="icon-signout"></i>&nbsp;&nbsp;Logout</a></li>
					</ul>
				</li>
			</ul>
			
			
		</div>
	</div>
</div>

lw/templates/includes/posting.html
<div class="span6">
	<p>This is an inclusion.</p>
	<form action="." method="post">
		<p>{% csrf_token %}</p>
		<textarea name="text" id="id_text" placeholder="What's up"></textarea>
		<button type="submit" class="btn">Post</button>
	</form>
</div>